export const artistsData = [
  {
    id: 1,
    name: "Mia Anderson",
    label: "Pop Artist",
    image: "/images/artists/Image-1.png",
    shortDescription: "Популярная поп-звезда.",
    fullDescription: "Миа Андерсон - одна из ведущих поп-артистов.",
    category: "dj",
    price: 8000,
  },
  {
    id: 2,
    name: "Benjamin Smith",
    label: "Country Artist",
    image: "/images/artists/Image-2.png",
    shortDescription: "Известный кантри-исполнитель.",
    fullDescription: "Бенджамин Смит - легенда кантри-музыки.",
    category: "mc",
    price: 9000,
  },
  {
    id: 3,
    name: "Charlotte Parker",
    label: "Rap Artist",
    image: "/images/artists/Image-3.png",
    shortDescription: "Топовый рэп-исполнитель.",
    fullDescription: "Шарлотта Паркер - звезда рэп-сцены.",
    category: "artist",
    price: 10000,
  },
  {
    id: 4,
    name: "Matthew Clark",
    label: "Metal Artist",
    image: "/images/artists/Image-4.png",
    shortDescription: "Звезда метал-сцены.",
    fullDescription: "Мэтью Кларк - легенда метал-музыки.",
    category: "dj",
    price: 7000,
  },
  {
    id: 5,
    name: "Elena Rossi",
    label: "Classical Soprano",
    image: "/images/artists/Image-5.png",
    shortDescription: "Известная оперная певица.",
    fullDescription:
      "Елена Росси - оперная певица, завоевавшая мировое признание.",
    category: "artist",
    price: 12000,
  },
  {
    id: 6,
    name: "Liam Scott",
    label: "Rock Guitarist",
    image: "/images/artists/Image-6.png",
    shortDescription: "Легендарный рок-гитарист.",
    fullDescription:
      "Лиам Скотт - виртуозный рок-гитарист с многолетним опытом.",
    category: "artist",
    price: 9500,
  },
  {
    id: 7,
    name: "Natalie Johnson",
    label: "Jazz Vocalist",
    image: "/images/artists/Image-7.png",
    shortDescription: "Популярная джазовая певица.",
    fullDescription:
      "Натали Джонсон - одна из самых талантливых джазовых вокалисток нашего времени.",
    category: "mc",
    price: 8500,
  },
  {
    id: 8,
    name: "Oliver Stone",
    label: "Electronic DJ",
    image: "/images/artists/Image-8.png",
    shortDescription: "Звезда электронной музыки.",
    fullDescription:
      "Оливер Стоун - известный диджей, работающий в жанре электронной музыки.",
    category: "dj",
    price: 6500,
  },
];
